export const biomarkersData = [
  // Complete Blood Count (CBC)
  {
    code: "WBC",
    name: "White Blood Cells",
    category: "CBC",
    canonicalUnit: "10^9/L",
    description: "White blood cell count, a measure of immune function",
    aliases: ["Leukocytes", "White Cell Count"],
  },
  {
    code: "RBC",
    name: "Red Blood Cells",
    category: "CBC",
    canonicalUnit: "10^12/L",
    description: "Red blood cell count",
    aliases: ["Erythrocytes", "Red Cell Count"],
  },
  {
    code: "HGB",
    name: "Hemoglobin",
    category: "CBC",
    canonicalUnit: "g/L",
    description: "Oxygen-carrying protein in red blood cells",
    aliases: ["Hgb", "Haemoglobin"],
  },
  {
    code: "HCT",
    name: "Hematocrit",
    category: "CBC",
    canonicalUnit: "L/L",
    description: "Percentage of blood volume occupied by red blood cells",
    aliases: ["Hct", "PCV", "Packed Cell Volume"],
  },
  {
    code: "MCV",
    name: "Mean Corpuscular Volume",
    category: "CBC",
    canonicalUnit: "fL",
    description: "Average size of red blood cells",
    aliases: [],
  },
  {
    code: "MCH",
    name: "Mean Corpuscular Hemoglobin",
    category: "CBC",
    canonicalUnit: "pg",
    description: "Average amount of hemoglobin per red blood cell",
    aliases: [],
  },
  {
    code: "MCHC",
    name: "Mean Corpuscular Hemoglobin Concentration",
    category: "CBC",
    canonicalUnit: "g/L",
    description: "Average concentration of hemoglobin in red blood cells",
    aliases: [],
  },
  {
    code: "PLT",
    name: "Platelets",
    category: "CBC",
    canonicalUnit: "10^9/L",
    description: "Blood clotting cells",
    aliases: ["Platelet Count", "Thrombocytes"],
  },
  {
    code: "RDW",
    name: "Red Cell Distribution Width",
    category: "CBC",
    canonicalUnit: "%",
    description: "Variation in red blood cell size",
    aliases: [],
  },
  {
    code: "LYMPH",
    name: "Lymphocyte Percentage",
    category: "CBC",
    canonicalUnit: "%",
    description: "Percentage of white blood cells that are lymphocytes",
    aliases: ["Lymphocytes %", "Lymph %", "Lymphocyte Count %"],
  },

  // Lipid Panel
  {
    code: "TC",
    name: "Total Cholesterol",
    category: "Lipid Panel",
    canonicalUnit: "mmol/L",
    description: "Total cholesterol level",
    aliases: ["Cholesterol"],
  },
  {
    code: "LDL",
    name: "LDL Cholesterol",
    category: "Lipid Panel",
    canonicalUnit: "mmol/L",
    description: "Low-density lipoprotein cholesterol",
    aliases: ["LDL-C", "Bad Cholesterol"],
  },
  {
    code: "HDL",
    name: "HDL Cholesterol",
    category: "Lipid Panel",
    canonicalUnit: "mmol/L",
    description: "High-density lipoprotein cholesterol",
    aliases: ["HDL-C", "Good Cholesterol"],
  },
  {
    code: "TG",
    name: "Triglycerides",
    category: "Lipid Panel",
    canonicalUnit: "mmol/L",
    description: "Blood fat levels",
    aliases: ["Trigs"],
  },
  {
    code: "VLDL",
    name: "VLDL Cholesterol",
    category: "Lipid Panel",
    canonicalUnit: "mmol/L",
    description: "Very low-density lipoprotein cholesterol",
    aliases: [],
  },

  // Comprehensive Metabolic Panel
  {
    code: "GLU",
    name: "Glucose",
    category: "Metabolic Panel",
    canonicalUnit: "mmol/L",
    description: "Blood sugar level",
    aliases: ["Blood Sugar", "Fasting Glucose", "Blood Glucose"],
  },
  {
    code: "BUN",
    name: "Blood Urea Nitrogen",
    category: "Metabolic Panel",
    canonicalUnit: "mmol/L",
    description: "Kidney function marker",
    aliases: ["Urea"],
  },
  {
    code: "CREAT",
    name: "Creatinine",
    category: "Metabolic Panel",
    canonicalUnit: "μmol/L",
    description: "Kidney function marker",
    aliases: [],
  },
  {
    code: "EGFR",
    name: "Estimated GFR",
    category: "Metabolic Panel",
    canonicalUnit: "mL/min/1.73m²",
    description: "Estimated glomerular filtration rate - kidney function",
    aliases: ["eGFR"],
  },
  {
    code: "NA",
    name: "Sodium",
    category: "Metabolic Panel",
    canonicalUnit: "mmol/L",
    description: "Electrolyte balance",
    aliases: ["Na+"],
  },
  {
    code: "K",
    name: "Potassium",
    category: "Metabolic Panel",
    canonicalUnit: "mmol/L",
    description: "Electrolyte balance",
    aliases: ["K+"],
  },
  {
    code: "CL",
    name: "Chloride",
    category: "Metabolic Panel",
    canonicalUnit: "mmol/L",
    description: "Electrolyte balance",
    aliases: ["Cl-"],
  },
  {
    code: "CO2",
    name: "Carbon Dioxide",
    category: "Metabolic Panel",
    canonicalUnit: "mmol/L",
    description: "Acid-base balance",
    aliases: ["Bicarbonate", "HCO3"],
  },
  {
    code: "CA",
    name: "Calcium",
    category: "Metabolic Panel",
    canonicalUnit: "mmol/L",
    description: "Bone and nerve function",
    aliases: [],
  },
  {
    code: "TP",
    name: "Total Protein",
    category: "Metabolic Panel",
    canonicalUnit: "g/L",
    description: "Total blood protein level",
    aliases: [],
  },
  {
    code: "ALB",
    name: "Albumin",
    category: "Metabolic Panel",
    canonicalUnit: "g/L",
    description: "Main blood protein",
    aliases: [],
  },
  {
    code: "BILI",
    name: "Bilirubin (Total)",
    category: "Metabolic Panel",
    canonicalUnit: "μmol/L",
    description: "Liver function marker",
    aliases: ["Total Bilirubin"],
  },
  {
    code: "ALP",
    name: "Alkaline Phosphatase",
    category: "Metabolic Panel",
    canonicalUnit: "U/L",
    description: "Liver and bone enzyme",
    aliases: ["Alk Phos"],
  },
  {
    code: "AST",
    name: "Aspartate Aminotransferase",
    category: "Metabolic Panel",
    canonicalUnit: "U/L",
    description: "Liver enzyme",
    aliases: ["SGOT"],
  },
  {
    code: "ALT",
    name: "Alanine Aminotransferase",
    category: "Metabolic Panel",
    canonicalUnit: "U/L",
    description: "Liver enzyme",
    aliases: ["SGPT"],
  },

  // Thyroid Panel
  {
    code: "TSH",
    name: "Thyroid Stimulating Hormone",
    category: "Thyroid Panel",
    canonicalUnit: "mIU/L",
    description: "Thyroid function marker",
    aliases: [],
  },
  {
    code: "T4",
    name: "Thyroxine",
    category: "Thyroid Panel",
    canonicalUnit: "nmol/L",
    description: "Thyroid hormone",
    aliases: ["Free T4", "FT4"],
  },
  {
    code: "T3",
    name: "Triiodothyronine",
    category: "Thyroid Panel",
    canonicalUnit: "nmol/L",
    description: "Thyroid hormone",
    aliases: ["Free T3", "FT3"],
  },

  // Iron Studies
  {
    code: "FE",
    name: "Iron",
    category: "Iron Studies",
    canonicalUnit: "μmol/L",
    description: "Serum iron level",
    aliases: ["Serum Iron"],
  },
  {
    code: "FERR",
    name: "Ferritin",
    category: "Iron Studies",
    canonicalUnit: "μg/L",
    description: "Iron storage protein",
    aliases: [],
  },
  {
    code: "TIBC",
    name: "Total Iron Binding Capacity",
    category: "Iron Studies",
    canonicalUnit: "μmol/L",
    description: "Iron transport capacity",
    aliases: [],
  },
  {
    code: "TSAT",
    name: "Transferrin Saturation",
    category: "Iron Studies",
    canonicalUnit: "%",
    description: "Iron saturation percentage",
    aliases: ["Iron Saturation"],
  },

  // Vitamins & Minerals
  {
    code: "VITD",
    name: "Vitamin D",
    category: "Vitamins",
    canonicalUnit: "nmol/L",
    description: "Vitamin D level",
    aliases: ["25-OH Vitamin D", "D3", "25-Hydroxyvitamin D"],
  },
  {
    code: "VITB12",
    name: "Vitamin B12",
    category: "Vitamins",
    canonicalUnit: "pmol/L",
    description: "Vitamin B12 level",
    aliases: ["Cobalamin"],
  },
  {
    code: "FOLATE",
    name: "Folate",
    category: "Vitamins",
    canonicalUnit: "nmol/L",
    description: "Folic acid level",
    aliases: ["Folic Acid"],
  },
  {
    code: "MG",
    name: "Magnesium",
    category: "Minerals",
    canonicalUnit: "mmol/L",
    description: "Magnesium level",
    aliases: [],
  },

  // Inflammatory Markers
  {
    code: "CRP",
    name: "C-Reactive Protein",
    category: "Inflammatory",
    canonicalUnit: "mg/L",
    description: "Inflammation marker",
    aliases: [],
  },
  {
    code: "HSCRP",
    name: "High-Sensitivity CRP",
    category: "Inflammatory",
    canonicalUnit: "mg/L",
    description: "High-sensitivity inflammation marker",
    aliases: ["hs-CRP"],
  },
  {
    code: "ESR",
    name: "Erythrocyte Sedimentation Rate",
    category: "Inflammatory",
    canonicalUnit: "mm/hr",
    description: "Inflammation marker",
    aliases: ["Sed Rate"],
  },

  // Diabetes Markers
  {
    code: "HBA1C",
    name: "Hemoglobin A1c",
    category: "Diabetes",
    canonicalUnit: "%",
    description: "Average blood sugar over 2-3 months",
    aliases: ["A1C", "Glycated Hemoglobin"],
  },
  {
    code: "FINS",
    name: "Fasting Insulin",
    category: "Diabetes",
    canonicalUnit: "pmol/L",
    description: "Fasting insulin level",
    aliases: ["Insulin"],
  },

  // Hormones
  {
    code: "TESTO",
    name: "Testosterone",
    category: "Hormones",
    canonicalUnit: "nmol/L",
    description: "Testosterone hormone level",
    aliases: ["Total Testosterone"],
  },
  {
    code: "CORT",
    name: "Cortisol",
    category: "Hormones",
    canonicalUnit: "nmol/L",
    description: "Stress hormone level",
    aliases: [],
  },
];

export const referenceRangesData = [
  // CBC - General adult ranges
  { code: "WBC", minValue: 4.5, maxValue: 11.0, unit: "10^9/L" },
  { code: "RBC", minValue: 4.5, maxValue: 5.5, unit: "10^12/L", sex: "male" },
  { code: "RBC", minValue: 4.0, maxValue: 5.0, unit: "10^12/L", sex: "female" },
  { code: "HGB", minValue: 130, maxValue: 170, unit: "g/L", sex: "male" },
  { code: "HGB", minValue: 120, maxValue: 160, unit: "g/L", sex: "female" },
  { code: "HCT", minValue: 0.38, maxValue: 0.50, unit: "L/L", sex: "male" },
  { code: "HCT", minValue: 0.36, maxValue: 0.44, unit: "L/L", sex: "female" },
  { code: "MCV", minValue: 80, maxValue: 100, unit: "fL" },
  { code: "MCH", minValue: 27, maxValue: 33, unit: "pg" },
  { code: "MCHC", minValue: 320, maxValue: 360, unit: "g/L" },
  { code: "PLT", minValue: 150, maxValue: 400, unit: "10^9/L" },
  { code: "RDW", minValue: 11.5, maxValue: 14.5, unit: "%" },
  { code: "LYMPH", minValue: 20, maxValue: 40, unit: "%" },

  // Lipid Panel
  { code: "TC", minValue: null, maxValue: 5.2, unit: "mmol/L" },
  { code: "LDL", minValue: null, maxValue: 3.4, unit: "mmol/L" },
  { code: "HDL", minValue: 1.0, maxValue: null, unit: "mmol/L", sex: "male" },
  { code: "HDL", minValue: 1.2, maxValue: null, unit: "mmol/L", sex: "female" },
  { code: "TG", minValue: null, maxValue: 1.7, unit: "mmol/L" },
  { code: "VLDL", minValue: 0.1, maxValue: 0.8, unit: "mmol/L" },

  // Metabolic Panel
  { code: "GLU", minValue: 3.9, maxValue: 5.6, unit: "mmol/L" },
  { code: "BUN", minValue: 2.5, maxValue: 7.1, unit: "mmol/L" },
  { code: "CREAT", minValue: 53, maxValue: 106, unit: "μmol/L", sex: "male" },
  { code: "CREAT", minValue: 44, maxValue: 80, unit: "μmol/L", sex: "female" },
  { code: "EGFR", minValue: 90, maxValue: null, unit: "mL/min/1.73m²" },
  { code: "NA", minValue: 136, maxValue: 145, unit: "mmol/L" },
  { code: "K", minValue: 3.5, maxValue: 5.0, unit: "mmol/L" },
  { code: "CL", minValue: 98, maxValue: 106, unit: "mmol/L" },
  { code: "CO2", minValue: 22, maxValue: 29, unit: "mmol/L" },
  { code: "CA", minValue: 2.15, maxValue: 2.55, unit: "mmol/L" },
  { code: "TP", minValue: 60, maxValue: 83, unit: "g/L" },
  { code: "ALB", minValue: 35, maxValue: 50, unit: "g/L" },
  { code: "BILI", minValue: 3, maxValue: 21, unit: "μmol/L" },
  { code: "ALP", minValue: 44, maxValue: 147, unit: "U/L" },
  { code: "AST", minValue: 10, maxValue: 40, unit: "U/L" },
  { code: "ALT", minValue: 7, maxValue: 56, unit: "U/L" },

  // Thyroid Panel
  { code: "TSH", minValue: 0.4, maxValue: 4.0, unit: "mIU/L" },
  { code: "T4", minValue: 12, maxValue: 22, unit: "nmol/L" },
  { code: "T3", minValue: 3.1, maxValue: 6.8, unit: "nmol/L" },

  // Iron Studies
  { code: "FE", minValue: 9, maxValue: 30, unit: "μmol/L" },
  { code: "FERR", minValue: 30, maxValue: 400, unit: "μg/L", sex: "male" },
  { code: "FERR", minValue: 13, maxValue: 150, unit: "μg/L", sex: "female" },
  { code: "TIBC", minValue: 45, maxValue: 72, unit: "μmol/L" },
  { code: "TSAT", minValue: 20, maxValue: 50, unit: "%" },

  // Vitamins
  { code: "VITD", minValue: 50, maxValue: 125, unit: "nmol/L" },
  { code: "VITB12", minValue: 148, maxValue: 590, unit: "pmol/L" },
  { code: "FOLATE", minValue: 7, maxValue: 36, unit: "nmol/L" },
  { code: "MG", minValue: 0.7, maxValue: 1.0, unit: "mmol/L" },

  // Inflammatory Markers
  { code: "CRP", minValue: null, maxValue: 10, unit: "mg/L" },
  { code: "HSCRP", minValue: null, maxValue: 3, unit: "mg/L" },
  { code: "ESR", minValue: null, maxValue: 15, unit: "mm/hr", sex: "male" },
  { code: "ESR", minValue: null, maxValue: 20, unit: "mm/hr", sex: "female" },

  // Diabetes Markers
  { code: "HBA1C", minValue: null, maxValue: 5.7, unit: "%" },
  { code: "FINS", minValue: 18, maxValue: 173, unit: "pmol/L" },

  // Hormones
  {
    code: "TESTO",
    minValue: 8.64,
    maxValue: 29.0,
    unit: "nmol/L",
    sex: "male",
  },
  {
    code: "TESTO",
    minValue: 0.52,
    maxValue: 2.4,
    unit: "nmol/L",
    sex: "female",
  },
  { code: "CORT", minValue: 138, maxValue: 690, unit: "nmol/L" },
];
